# --- RBAC objects ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xdr-agent-updater
  namespace: cortex-xdr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xdr-agent-updater
  namespace: cortex-xdr
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xdr-agent-updater
  namespace: cortex-xdr
subjects:
- kind: ServiceAccount
  name: xdr-agent-updater
  namespace: cortex-xdr
roleRef:
  kind: Role
  name: xdr-agent-updater
  apiGroup: rbac.authorization.k8s.io

# --- Immediate one-shot Job ---
apiVersion: batch/v1
kind: Job
metadata:
  name: xdr-agent-updater-manual
  namespace: cortex-xdr
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: xdr-agent-updater
      restartPolicy: Never
      containers:
      - name: updater
        image: bajacloud/xdr-agent-updater:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: docker-config
          mountPath: /root/.docker
          readOnly: true
      volumes:
      - name: docker-config
        secret:
          secretName: cortex-docker-secret
          items:
          - key: .dockerconfigjson
            path: config.json

